language: android
sudo: false
android:
  components:
    - tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-27.1.0

    # The SDK version used to compile your project
    - android-26
    - android-27
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
jdk: oraclejdk8
os:
    - linux